name: setup
description: Sets up development environment
inputs: {}
outputs: {}
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
      with:
        package_json_file: doc/package.json
    - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        cache: pnpm
        cache-dependency-path: doc/pnpm-lock.yaml
        node-version-file: doc/package.json
    - run: pnpm i --frozen-lockfile
      working-directory: doc
      shell: bash
