name: muffet
version: latest
version-script: prime/bin/muffet --version
summary: Fast website link checker in Go
description: |
  Muffet is a website link checker which scrapes and inspects all pages in a
  website recursively.

grade: stable
confinement: strict

apps:
  muffet:
    command: bin/muffet
    plugs:
      - network

parts:
  go:
    source-tag: go1.10.1
  muffet:
    plugin: go
    after:
      - go
    source: https://github.com/raviqqe/muffet.git
    source-type: git
    go-importpath: github.com/raviqqe/muffet
