name: document
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: document-${{ github.ref }}
  cancel-in-progress: true
jobs:
  web_build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: doc
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - run: node --run build
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v4
        with:
          path: doc/dist
      - uses: actions/deploy-pages@v4
        if: github.ref == 'refs/heads/main'
  web_lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: doc
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - run: node --run lint
  web_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - run: node --run build -- --site http://localhost:4321
        working-directory: doc
      - run: node --run preview &
        working-directory: doc
      - run: go run . --buffer-size 8192 http://localhost:4321/muffet/
  document:
    needs:
      - web_build
      - web_lint
      - web_test
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: for result in ${{ join(needs.*.result, ' ') }}; do [ $result = success ]; done
